classifier:
  class_path: src.models.classification.fa.FAFT
  init_args:
    beta: 0.45
    eta: 1.0
    pixel_mean: [0.0, 0.0, 0.0]
    pixel_std: [1.0, 1.0, 1.0]
    classifier:
      class_path: src.models.classification.erm.ViT
      init_args:
        image_size: 224
        patch_size: 32
        num_classes: 65
        dim: 768
        depth: 12
        heads: 12
        mlp_dim: 3072
        pool: 'cls' # ['cls', 'mean'] 
        channels: 3
        dim_head: 64 
        dropout_rate: 0.
        emb_dropout_rate: 0.
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-3
scheduler:
  class_path: torch.optim.lr_scheduler.LinearLR
  # init_args:
  #   T_max: 30
