classifier:
  class_path: src.models.classification.fa.FAST
  init_args:
    beta: 0.45
    pixel_mean: [0.0, 0.0, 0.0]
    pixel_std: [1.0, 1.0, 1.0]
    nst:
      class_path: src.models.nst.ada_in.AdaINModel
      init_args:
        alpha: 0.5
        encoder: src.models.nst.AdaINEncoder
        decoder: src.models.nst.AdaINDecoder
        ckpt_path: experiments/nst/version_14/checkpoints/last.ckpt
    classifier:
      class_path: src.models.classification.erm.ResNet18
      init_args:
        num_classes: 65
        pretrained_url: https://download.pytorch.org/models/resnet18-5c106cde.pth
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 1e-5
scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  init_args:
    T_0: 30