network: 
  class_path: src.models.nst.itn.ItnModel
  # init_args:
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.001
scheduler:
  class_path: torch.optim.lr_scheduler.StepLR
  init_args:
    step_size: 30
    gamma: 0.00005