network:
  class_path: src.models.classification.fa.fagt
  init_args:
    classifie: src.models.classification.erm.ResNet18
    nst: src.models.nst.AdaINModel
optimizer:
  class_path: torch.optim.sgd
scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
