classifier:
  class_path: src.models.classification.erm.SmallConvNet
  init_args:
    num_classes: 10
    pretrained_path: null
optimizer:
  class_path: torch.optim.SGD
  init_args:
    momentum: 0.9
    lr: 0.03
    weight_decay: 5e-4
scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  init_args:
    T_0: 50