classifier:
  class_path: src.models.classification.erm.ViT
  init_args:
    image_size: 32
    patch_size: 8
    num_classes: 10
    dim: 128
    depth: 2
    heads: 1
    mlp_dim: 64
    pool: 'cls' # ['cls', 'mean'] 
    channels: 3
    dim_head: 64 
    dropout_rate: 0.
    emb_dropout_rate: 0.
optimizer:
  class_path: torch.optim.Adam
scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  init_args:
    T_0: 30