classifier:
  class_path: src.models.classification.fa.FAST
  init_args:
    beta: 0.7
    pixel_mean: [0.0, 0.0, 0.0]
    pixel_std: [1.0, 1.0, 1.0]
    nst:
      class_path: src.models.nst.ada_in.AdaINModel
      init_args:
        alpha: 0.35
        encoder: 
          class_path: src.models.nst.AdaINEncoder
          init_args:
            pretrain: True
        decoder: 
          class_path: src.models.nst.AdaINDecoder
          init_args:
            pretrain: True
    classifier:
      class_path: src.models.classification.erm.ResNet18
      init_args:
        num_classes: 7
        pretrained_url: https://download.pytorch.org/models/resnet18-5c106cde.pth
optimizer:
  class_path: torch.optim.SGD
  init_args:
    momentum: 0.9
    lr: 0.001
    weight_decay: 5e-4
scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  init_args:
    T_0: 30