classifier:
  class_path: src.models.classification.erm.SmallConvNet
  init_args:
    num_classes: 10
    pretrained_path: None
optimizer:
  class_path: torch.optim.SGD
  init_args:
    lr: 5e-4
scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 30