model:
  classifier:
    class_path: src.models.classification.erm.ResNet18
    init_args:
      ...
  optimizer:
    class_path: Adam
    init_args:
      ...
  scheduler:
    class_path: CosineAnnealingLR
    init_args:
      ...
