classifier:
  class_path: src.models.classification.erm.ViT
  init_args:
    image_size: 1
    patch_size: 1
    num_classes: 10
    dim: 1
    depth: 1
    heads: 1
    mlp_dim: 1
    pool: 'cls' # ['cls', 'mean'] 
    channels: 3
    dim_head: 64 
    dropout: 0.
    emb_dropout: 0.
optimizer:
  class_path: torch.optim.Adam
scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 30