classifier:
  class_path: src.models.classification.fa.FAFT
  init_args:
    classifier:
      class_path: src.models.classification.erm.ViT
      init_args:
        image_size: 224
        patch_size: 16
        num_classes: 2
        dim: 128
        depth: 2
        heads: 1
        mlp_dim: 64
        pool: 'cls' # ['cls', 'mean'] 
        channels: 3
        dim_head: 64 
        dropout: 0.
        emb_dropout: 0.
optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 1e-5
scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    T_max: 30
